# Generated by Django 4.0.3 on 2022-03-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djJson', '0005_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='nbr_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
